app = App#14:516{owner:13_1154,mng:17_0,versions:[105],dslPackage:flow2b.xero,name:,description:,uuid:189523713439291072855282057135459059560} v3
dslPackage = flow2b.xero
releaseNotes = <p>B3733&nbsp;Payment not pulled from Xero...</p><p><br></p><p><span data-auto-link="true" data-href="https://flow2b.com/s/#13_1/flow2b.net.dev.Bug/form/15_28440"><a href="javascript:;" data-href="#13_1/flow2b.net.dev.Bug/form/15_28440">https://flow2b.com/s/#13_1/flow2b.net.dev.Bug/form/15_28440</a></span><br></p><p><br></p><p>This bug is related to issue with BatchPayment in XeroAPI</p><p><a href="https://community.xero.com/developer/discussion/81118345/"><span data-auto-link="true" data-href="https://community.xero.com/developer/discussion/81118345/">https://community.xero.com/developer/discussion/81118345/</span></a><br></p><p><br></p>
@rid = #12:2208
touchedOn = Sat Feb 02 08:32:56 UTC 2019
version = 5.17.5
uuid = 179760652143395114685279225628208478459
dependencies = [{dslPackage:flow2b.inv.order,version:[11.0.0, 12.0.0),channel:Pretest}, {dslPackage:flow2b.integ,version:,channel:Pretest}, {dslPackage:flow2b.acc.asset,version:,channel:Pretest}]
status = Canceled
